# Generated by Django 3.0.6 on 2020-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anometa',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ano', models.PositiveIntegerField()),
                ('meta', models.IntegerField()),
            ],
            options={
                'db_table': 'AnoMeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbid', models.CharField(db_column='imdbID', max_length=45)),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('poster', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Filmes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filmesassistidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posano', models.IntegerField(db_column='posAno')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('inedito', models.IntegerField()),
            ],
            options={
                'db_table': 'FilmesAssistidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
