# Generated by Django 3.0.6 on 2020-05-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
