# Generated by Django 3.0.6 on 2020-05-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_teste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anometa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filmes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filmesassistidos',
            options={'managed': True},
        ),
    ]
